language: node_js
node_js:
  - "4.2"

sudo: false
cache:
  directories:
    - node_modules
    - bower_components
    
before_script:
  - npm install -g bower
  - export PHANTOMJS_BIN=/usr/local/phantomjs/bin/phantomjs
  - bower install
  
script: gulp test